### ISSUE TITLE
Label is not show. it need z index to show above 

### ISSUE THREAD

**Issue by MohsinAliSoomro** [junhoyeo/frogress#4]
![image](https://user-images.githubusercontent.com/39213044/150179510-bc866ce6-df7e-4667-bec1-a49e40252ef1.png)

**Comment by junhoyeo** [comment]
Thanks for raising an issue here!  
I intended to pass fewer styles to the label so people can pass styles to the custom label themselves.
But I'll check. Until that how about passing your styles to the `CustomLabelComponent`'s container manually?

```tsx
<LineProgressBar
  label={(value: number) => <CustomLabelComponent percent={value} />}
  percent={45}
  rounded={36}
  height={36}
/>
```

**Comment by junhoyeo** [comment]
`label` is just an optional function, so I cannot/will not add more styles. Please style your `CustomLabelComponent` yourselves!

```tsx
    ...
  </Progress>
  {label?.(percent)}
</Container>
```
