### ISSUE TITLE
Warning: Received NaN for the `offset` attribute. If this is expected, cast the value to a string.

### ISSUE THREAD

**Issue by ItsFlash10** [junhoyeo/frogress#5]
<img width="955" alt="Screenshot 2022-02-24 at 12 45 32 AM" src="https://user-images.githubusercontent.com/57027429/155391150-9eef2319-b0dc-45d6-a383-94db6cc535c8.png">

I have been getting this warning when using the Linear Progress Bar

This is my code:
<img width="476" alt="Screenshot 2022-02-24 at 12 47 09 AM" src="https://user-images.githubusercontent.com/57027429/155391406-b09e70c7-18fb-4163-a3bc-724ea84fdeec.png">

**Comment by junhoyeo** [comment]
lol afik that wasn't expected.
Thanks! I'll try to add a fix ❤️

**Comment by junhoyeo** [comment]
@ItsFlash10 A bit late but fixed in `@frogress/line@1.2.1`! Thanks for using Frogress 🙇
