### ISSUE TITLE
Could not resolve dependency tree

### ISSUE THREAD

**Issue by Blademaster680** [junhoyeo/frogress#6]
I am getting a `could not resolve dependency tree` error when trying to run npm install on my project that has frogress line installed.
It seems to be failing over the framer-motion dependancy

![image](https://user-images.githubusercontent.com/17591254/170008973-f185078a-78af-486c-852f-5fe1c943896b.png)

**Comment by junhoyeo** [comment]
@Blademaster680 Thanks for your issue! Fixed in `@frogress/line@1.2.1`.
